print("what is your name?")
name= str(input())
print("hello. What is your age?")
age= int(input())
print("hello " + name + " in a year you will be " + str(age +1))
print("where do you live?")
home= input()
print(home + " will be destroyed in one week")
